name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Run the unit tests
      run: npm test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-with-vscode:
    runs-on: ubuntu-latest
    - name: pull lsp code
      uses: actions/checkout@v2
    - name: Setup Node env
      uses: actions/setup-node@v2.1.2
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12.x
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: pull vscode-extension code
      uses: actions/checkout@v2
      repository: fabric8-analytics/fabric8-analytics-vscode-extension
      path: vscode-extension
    - name: Install vsce
      run: npm i -g vsce
    - name: Install local lsp
      run: npm i ../output
      working-directory: ./vscode-extension
    - name: Install Dependencies
      run: npm ci
      working-directory: ./vscode-extension
    - name: VSCE prepublish
      run: vsce package
      working-directory: ./vscode-extension
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension Build - ${{ github.event.pull_request.number }}
        path: ./vscode-extension/*.vsix
